POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Check Out This Full Stack Course!!!",
    "author": "Mdan22",
    "url": "https://fullstackopen.com/en/",
    "likes": 0
}