POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Hello, Blog!",
    "author": "Akira Taguchi",
    "url": "https://akirataguchi115.github.io/misc/2023/12/31/hello-blog.html",
    "likes": 0
}